### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by SeekPoint** [manderous/TextClassification-MeiTuan-FeatureExtraction-Classifier#1]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/TextClassification-MeiTuan-FeatureExtraction-Classifier$ python3.6 boost_tree.py
field_names: ['', 'Label', 'Sentence', 'feature_pos', 'feature_fresq', 'feature_sentiment', 'feature_slen', 'feature_senti_num', 'feature_enti_num']
train_feat:
 ['找到d座电梯上去很好找的' '5' '0' '0' '8' '0' '1']
train_feat:
 ['None' '5' '0' '0' '8' '0' '1']
Traceback (most recent call last):
  File "boost_tree.py", line 126, in <module>
    train_data = to_libsvm(train_feat)
  File "boost_tree.py", line 99, in to_libsvm
    fv = get_feat_id_val(i, d[i])
  File "boost_tree.py", line 89, in get_feat_id_val
    return feat_map[feat_name], to_float(feat_val)
  File "boost_tree.py", line 80, in to_float
    return float(x)
ValueError: could not convert string to float: '2 5'
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/TextClassification-MeiTuan-FeatureExtraction-Classifier$

**Comment by Youarerare** [comment]
你好，我同样遇到这个问题，请问你当时解决这个问题了吗

**Comment by Youarerare** [comment]
> 你好，我同样遇到这个问题，请问你当时解决这个问题了吗

找到原因了，field和train.csv中的特征对不上,将[此处代码](https://github.com/manderous/TextClassification-MeiTuan-FeatureExtraction-Classifier/blob/c3d444f187dcb56f0e87f8facaf9117e5a4deef1/boost_tree.py#L14)替换为如下代码即可

CAT_FEAT = [3]
NUM_FEAT = [5, 4, 6]
SET_FEAT = [1, 2]
FEAT_TYPE = {0: 'text', 1: 'set', 2: 'set', 3: 'cat', 4: 'num', 5: 'num', 6: 'num'}
